version: '3.8'

services:
  api:
    build: .
    container_name: compliance-api
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-}@redis:6379/0
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./local_sessions.db}
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - compliance-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: compliance-redis
    ports:
      - "6379:6379"
    command: >
      sh -c "
      if [ -n \"${REDIS_PASSWORD}\" ]; then
        redis-server --requirepass ${REDIS_PASSWORD}
      else
        redis-server
      fi
      "
    volumes:
      - redis-data:/data
    networks:
      - compliance-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  redis-data:

networks:
  compliance-network:
    driver: bridge
