version: '3.8'

services:
  api:
    build: .
    container_name: compliance-api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./local_sessions.db
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - API_KEYS=${API_KEYS:-demo_key_123}
      - DEBUG=${DEBUG:-true}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8000}
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - compliance-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: compliance-redis
    ports:
      - "6379:6379"
    command: >
      sh -c "
      if [ -n \"${REDIS_PASSWORD}\" ]; then
        redis-server --requirepass ${REDIS_PASSWORD}
      else
        redis-server
      fi
      "
    volumes:
      - redis-data:/data
    networks:
      - compliance-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  redis-data:

networks:
  compliance-network:
    driver: bridge
